name: Dev Release

on:
  push:
    branches:
      - main

jobs:
  
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    concurrency: DEV

    steps:
      - name: Run a one-line script
        run: echo Hello from DEV environment!
  