name: Release Workflow

on:
  workflow_dispatch:

jobs:
  
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    concurrency: DEV

    steps:
      - name: Run a one-line script
        run: echo Hello from DEV environment!

  QA:
    runs-on: ubuntu-latest
    environment: QA
    concurrency: QA
    needs: DEV

    steps:
      - name: Run a one-line script
        run: echo Hello from QA environment!

  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    concurrency: PROD
    needs: QA

    steps:
      - name: Run a one-line script
        run: echo Hello from PROD environment!
    
      - name: Display GitHub Actions Run URL
        run: | 
          RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" 
          echo "The URL for this GitHub Actions run is: $RUN_URL" 
          echo "## GitHub Actions Run URL" >> $GITHUB_STEP_SUMMARY 
          echo "$RUN_URL" >> $GITHUB_STEP_SUMMARY
          echo "$RUN_URL" >> $GITHUB_OUTPUT
  