name: PROD Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:
  

jobs:

  QA:
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from QA environment!
          echo run_id = ${{ github.run_id }}
          echo sha = ${{ github.sha }}
          echo ref = ${{ github.ref }}
          echo event_name = ${{ github.event_name }}
          echo default_branch = ${{ github.event.repository.default_branch }}
          echo test_var = ${{ vars.TEST_VAR }}

  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    needs: QA

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from QA environment!
          echo run_id = ${{ github.run_id }}
          echo sha = ${{ github.sha }}
          echo ref = ${{ github.ref }}
          echo event_name = ${{ github.event_name }}
          echo default_branch = ${{ github.event.repository.default_branch }}
          echo test_var = ${{ vars.TEST_VAR }}
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/}-${tag}" \
              --generate-notes