name: PROD Release

on:
  push:
    tags:
      - v*
  

jobs:

  QA:
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from QA environment!
          echo ${{ github.head_ref }}.${{ github.sha }}

  PROD:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from PROD environment!
          echo ${{ github.head_ref }}.${{ github.sha }}