name: PROD Release

on:
  push:
    tags:
      - v*
  

jobs:

  QA:
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from QA environment!
          echo run_id = ${{ github.run_id }}
          echo sha = ${{ github.sha }}
          echo ref = ${{ github.ref }}
          echo head_ref = ${{ github.head_ref }}
          echo environment = ${{ github.event.deployment.environment }}"

  PROD:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from PROD environment!
          echo ${{ github.head_ref }}.${{ github.sha }}