name: PROD Release

on:
  push:
    tags:
      - v*
  

jobs:

  QA:
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from QA environment!
          echo run_id = ${{ github.run_id }}
          echo sha = ${{ github.sha }}
          echo ref = ${{ github.ref }}
          echo event_name = ${{ github.event_name }}
          echo default_branch = ${{ github.event.repository.default_branch }}

  PROD:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from QA environment!
          echo run_id = ${{ github.run_id }}
          echo sha = ${{ github.sha }}
          echo ref = ${{ github.ref }}
          echo event_name = ${{ github.event_name }}
          echo default_branch = ${{ github.event.repository.default_branch }}