name: PROD Release

on:
  push:
    tags:
      - v*
  

jobs:

  QA:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Run a one-line script
        run: echo Hello from QA environment!