name: DEV and QA Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  
  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from QA environment!
          echo run_id = ${{ github.run_id }}
          echo sha = ${{ github.sha }}
          echo ref = ${{ github.ref }}
          echo event_name = ${{ github.event_name }}
          echo default_branch = ${{ github.event.repository.default_branch }}
          echo test_var = ${{ vars.TEST_VAR }}
      - name: Put current date into a variable
        run: |
          echo & Get-Date -format yyyy-MM-dd
          $NOW=& Get-Date -format yyyy-MM-dd
          echo "NOW=$NOW" >> $env:GITHUB_ENV

  # QA:
  #   runs-on: ubuntu-latest
  #   environment: QA
  #   needs: DEV

  #   steps:
  #     - name: Run a one-line script
  #       run: |
  #         echo Hello from QA environment!
  #         echo run_id = ${{ github.run_id }}
  #         echo sha = ${{ github.sha }}
  #         echo ref = ${{ github.ref }}
  #         echo event_name = ${{ github.event_name }}
  #         echo default_branch = ${{ github.event.repository.default_branch }}
  #         echo test_var = ${{ vars.TEST_VAR }}

