name: DEV and QA Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  
  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from QA environment!
          echo run_id = ${{ github.run_id }}
          echo sha = ${{ github.sha }}
          echo ref = ${{ github.ref }}
          echo head_ref = ${{ github.head_ref }}
          echo environment = ${{ github.event.deployment.environment }}"

  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from QA environment!
          echo ${{ github.head_ref }}.${{ github.sha }}
