name: DEV and QA Workflows

on:
  workflow_dispatch:

jobs:
  
  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Run a one-line script
        run: echo Hello from DEV environment!

  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV

    steps:
      - name: Run a one-line script
        run: echo Hello from QA environment!
