name: DEV and QA Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  
  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from DEV environment!
          echo ${{ github.event.head_commit.message }}

  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV

    steps:
      - name: Run a one-line script
        run: |
          echo Hello from QA environment!
          echo ${{ github.event.head_commit.message }}
