name: PROD Workflow

on:
  workflow_run:
    workflows: ["DEV and QA Workflows"]
    types:
      - completed


jobs:
  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Run a one-line script
        run: echo Hello from PROD environment!
